add option to see all branches

diff --git a/commands/git-branches b/commands/git-branches
--- a/commands/git-branches
+++ b/commands/git-branches
@@ -1,2 +1,23 @@
 #!/usr/bin/env bash
-hub browse -- branches/yours
+
+include_remote=""
+track=""
+
+while getopts ":a" opt; do
+  case $opt in
+    a)
+      all=true
+      shift
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+  esac
+done
+
+if [ -n "$all" ]; then
+    hub browse -- branches
+else
+    hub browse -- branches/yours
+fi
